import type { Metadata } from 'next';
import './globals.css';
import { UserProvider } from '@auth0/nextjs-auth0/client';
import Navbar from './components/Navbar/Navbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider>
        <body>
          <Navbar />
          <div className="p-8">{children}</div>
        </body>
      </UserProvider>
    </html>
  );
}
